Welcome to "Public_FTPD" %U

You are user %N out of a maximum of %M authorized logins.
Current time is %T.
The administrator can be reached here: %E

Statistics since: Thu Mar 26 00:13:52 2009

Top 10 Uploaders:
_________________
bbb: 3910763 KB
whk: 2523949 KB
wbkk: 1119582 KB
temp2: 474143 KB
jc: 463209 KB
yanx: 222418 KB
annopc: 167293 KB
walmart: 157469 KB
hut: 143241 KB
webxfer: 88203 KB

Top 10 Downloaders:
___________________
bbb: 10023121 KB
winsomewood: 6084471 KB
wbkk: 4816308 KB
whk: 3160438 KB
jc: 1534855 KB
temp2: 894633 KB
walmart: 359732 KB
hut: 263900 KB
target.com_9779: 168716 KB
webxfer: 63770 KB


Generated on Tue Feb 23 10:49:49 PST 2010

