development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: postgresql
  host: localhost
  username: root
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: winsome
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
