default: &default
  adapter: postgresql
  host: 192.168.161.189
  username: "postgres"
  password: "m4yfL#$R"
  database: www
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

production:
  <<: *default
