module ContactHelper
  def grouped_states
    {"United States" =>
      [["Alabama (AL)", "Alabama (AL)"],
      ["Alaska (AK)", "Alaska (AK)"],
      ["Arizona (AZ)", "Arizona (AZ)"],
      ["Arkansas (AR)", "Arkansas (AR)"],
      ["California (CA)", "California (CA)"],
      ["Colorado (CO)", "Colorado (CO)"],
      ["Connecticut (CT)", "Connecticut (CT)"],
      ["Delaware (DE)", "Delaware (DE)"],
      ["District of Columbia (DC)", "District of Columbia (DC)"],
      ["Florida (FL)", "Florida (FL)"],
      ["Georgia (GA)", "Georgia (GA)"],
      ["Guam (GU)", "Guam (GU)"],
      ["Hawaii (HI)", "Hawaii (HI)"],
      ["Idaho (ID)", "Idaho (ID)"],
      ["Illinois (IL)", "Illinois (IL)"],
      ["Indiana (IN)", "Indiana (IN)"],
      ["Iowa (IA)", "Iowa (IA)"],
      ["Kansas (KS)", "Kansas (KS)"],
      ["Kentucky (KY)", "Kentucky (KY)"],
      ["Louisiana (LA)", "Louisiana (LA)"],
      ["Maine (ME)", "Maine (ME)"],
      ["Maryland (MD)", "Maryland (MD)"],
      ["Massachusetts (MA)", "Massachusetts (MA)"],
      ["Michigan (MI)", "Michigan (MI)"],
      ["Minnesota (MN)", "Minnesota (MN)"],
      ["Mississippi (MS)", "Mississippi (MS)"],
      ["Missouri (MO)", "Missouri (MO)"],
      ["Montana (MT)", "Montana (MT)"],
      ["Nebraska (NE)", "Nebraska (NE)"],
      ["Nevada (NV)", "Nevada (NV)"],
      ["New Hampshire (NH)", "New Hampshire (NH)"],
      ["New Jersey (NJ)", "New Jersey (NJ)"],
      ["New Mexico (NM)", "New Mexico (NM)"],
      ["New York (NY)", "New York (NY)"],
      ["North Carolina (NC)", "North Carolina (NC)"],
      ["North Dakota (ND)", "North Dakota (ND)"],
      ["Ohio (OH)", "Ohio (OH)"],
      ["Oklahoma (OK)", "Oklahoma (OK)"],
      ["Oregon (OR)", "Oregon (OR)"],
      ["Pennyslvania (PA)", "Pennyslvania (PA)"],
      ["Puerto Rico (PR)", "Puerto Rico (PR)"],
      ["Rhode Island (RI)", "Rhode Island (RI)"],
      ["South Carolina (SC)", "South Carolina (SC)"],
      ["South Dakota (SD)", "South Dakota (SD)"],
      ["Tennessee (TN)", "Tennessee (TN)"],
      ["Texas (TX)", "Texas (TX)"],
      ["Utah (UT)", "Utah (UT)"],
      ["Vermont (VT)", "Vermont (VT)"],
      ["Virginia (VA)", "Virginia (VA)"],
      ["Virgin Islands (VI)", "Virgin Islands (VI)"],
      ["Washington (WA)", "Washington (WA)"],
      ["West Virginia (WV)", "West Virginia (WV)"],
      ["Wisconsin (WI)", "Wisconsin (WI)"],
      ["Wyoming (WY)", "Wyoming (WY)"]],
    "Canada" =>
      [["Alberta (AB)", "Alberta (AB)"],
      ["British Columbia (BC)", "British Columbia (BC)"],
      ["Manitoba (MB)", "Manitoba (MB)"],
      ["New Brunswick (NB)", "New Brunswick (NB)"],
      ["Newfoundland and Labrador (NL)", "Newfoundland and Labrador (NL)"],
      ["Northwest Territories (NT)", "Northwest Territories (NT)"],
      ["Nova Scotia (NS)", "Nova Scotia (NS)"],
      ["Nunavut (NU)", "Nunavut (NU)"],
      ["Prince Edward Island (PE)", "Prince Edward Island (PE)"],
      ["Saskatchewan (SK)", "Saskatchewan (SK)"],
      ["Ontario (ON)", "Ontario (ON)"],
      ["Quebec (QC)", "Quebec (QC)"],
      ["Yukon (YT)", "Yukon (YT)"]]
    }
  end
end
